#!/usr/bin/env bash

# This script should never be run standalone. It should always be executed thru the `pkg` script

# Remove packages from the package list
source "${PKG_DIR}/common"
rm_formula "$@"
