#!/usr/bin/env bash

# This script should never be run standalone. It should always be executed thru the `pkg` script

# Add new homebrew taps into the tap list
source "${PKG_DIR}/common"
add_tap "$@"
