#!/usr/bin/env bash

usage() {
  echo -n "$(basename "$0" | tr -s '-' ' ')

A script to add a commit for mirroring any
git.sr.ht codebases to Github.

  Options:
    -h, --help          Display this help and exit
"
}

while :; do
  flag=${1:-}

  case "$flag" in
  -h | -\? | --help)
    usage
    exit
    ;;
  --) # Demarcates end of all options.
    shift
    break
    ;;
  -?*) # Handle any unknown options.
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
  *) # End of all options if nothing matches
    break ;;
  esac

  shift
done

main() {
  mkdir .builds
  cp --recursive ~/.dotfiles/git/template/srht/build/mirror.yml .builds/mirror.yml
  git add .builds/mirror.yml

  if test -f .builds/mirror.yml; then
    echo "Sourcehut build manifest for mirroring repository already exists. Updating."
    git commit --message "Updating sr.ht build manifest for mirroring to Github"
  else
    echo "Adding Sourcehut build manifest for mirroring repository to Github"
    git commit --message "Add sr.ht build manifest for mirroring to Github"
  fi
}

main "$@"
