#!/usr/bin/env bash

toggle_notepad() {
  notepad_exists=$(notepad_exists)
  if [[ "$notepad_exists" -lt 1 ]]; then
    launch_notepad
    while ! ps h -C obsidian >/dev/null; do
      sleep .1
    done
    sleep 1
    position_notepad
  fi

  focus_notepad
}

notepad_exists() {
  pgrep --full "obsidian" | wc --lines
}

launch_notepad() {
  obsidian &
}

position_notepad() {
  swaymsg "[instance=obsidian] move scratchpad"
  resize_notepad
}

resize_notepad() {
  swaymsg "[instance=obsidian] resize set 2560 1440"
  swaymsg "[instance=obsidian] move absolute position center"
}

focus_notepad() {
  resize_notepad
  swaymsg "[instance=obsidian] scratchpad show"
}

toggle_notepad
