#! /usr/bin/env bash

ls /Applications/ /Applications/Utilities/ /System/Applications/ /System/Applications/Utilities/ |
  grep '\.app$' |
  sed 's/\.app$//g' |
  sort |
  choose |
  xargs -I {} open -a "{}.app"
