#!/usr/bin/env bash

defaultKeyname="id_ed25519"
keyname="$1"
dest="$HOME/.config/sops/age/keys.txt"

mkdir -p ~/.config/sops/age

op item get "${keyname:-$defaultKeyname}" --reveal --fields "private key" |
  nix run nixpkgs#ssh-to-age -- -private-key >"$dest" &&
  echo "Key saved to $dest"

pubkey=$(nix shell nixpkgs#age -c age-keygen -y "$dest")
echo "Public key: $pubkey"
