#!/usr/bin/env bash

defaultKeyname="id_ed25519"
keyname="$1"
destDir="/var/lib/sops-nix"
dest="${destDir}/key.txt"

sudo mkdir -p "${destDir}"

op item get "${keyname:-$defaultKeyname}" --reveal --fields "private key" |
  nix run nixpkgs#ssh-to-age -- -private-key | sudo tee "$dest" >/dev/null &&
  echo "Key saved to $dest"

pubkey=$(nix shell nixpkgs#age -c age-keygen -y "$dest")
echo "Public key: $pubkey"
