#!/usr/bin/env bash
set -e
set -u
set -o pipefail

if hash pbcopy 2>/dev/null; then
  exec pbcopy
elif hash wl-copy 2>/dev/null; then
  exec wl-copy --primary
else
  rm -f /tmp/clipboard 2>/dev/null
  if [ $# -eq 0 ]; then
    cat >/tmp/clipboard
  else
    cat "$1" >/tmp/clipboard
  fi
fi
