#!/usr/bin/env bash
set -e
set -u
set -o pipefail

if hash pbpaste 2>/dev/null; then
  exec pbpaste
elif hash wl-paste 2>/dev/null; then
  exec wl-paste --primary
elif [[ -e /tmp/clipboard ]]; then
  exec cat /tmp/clipboard
else
  echo ''
fi
