return {
  language_servers = {
    "basedpyright",
    "bashls",
    "biome",
    "dockerls",
    "gopls",
    "html",
    "jsonls",
    "lua_ls",
    "marksman",
    "nil_ls",
    "postgres_lsp",
    "rubocop",
    "ruby_lsp",
    "ruff",
    "sqls",
    "svelte",
    "taplo",
    "terraformls",
    "tflint",
    "ts_ls",
    "vimls",
    "vuels",
    "zls",
  },
  formatters = {
    bash = { "shfmt", "shellcheck" },
    css = { "biome" },
    go = { "gofumpt", "goimports", "gci" }, -- important that gci comes AFTER goimports so that imports are added THEN sorted.
    hcl = { "packer_fmt" },
    html = { "htmlbeautifier", "prettierd" },
    javascript = { "biome" },
    json = { "fixjson", "biome", "jq" },
    lua = { "stylua" },
    markdown = { "markdownlint", "prettierd" },
    nix = { "nixfmt" },
    python = { "ruff_fix", "ruff_format", "ruff_organize_imports" },
    ruby = { "rubyfmt" },
    sh = { "shfmt", "shellcheck" },
    terraform = { "terraform_fmt" },
    tofu = { "tofu_fmt" },
    toml = { "taplo" },
    typescript = { "biome" },
    zig = { "zigfmt" },
    vue = { "prettierd" },
    yaml = { "prettierd", "yamlfmt" },
    ["_"] = { "trim_whitespace", "trim_newlines", "squeeze_blanks" },
  },
  linters = {
    -- shellcheck is included in bashls, we don't need to double lint
    -- bash = { "shellcheck" },
    css = { "biomejs" },
    docker = { "hadolint" },
    git = { "gitlint" },
    go = { "golangcilint" },
    javascript = { "biomejs" },
    json = { "jsonlint" },
    lua = { "selene" },
    markdown = { "markdownlint" },
    python = { "mypy_venv", "ruff" },
    ruby = { "rubocop" },
    sh = { "shellcheck" },
    sql = { "sqlfluff" },
    terraform = { "tflint", "tfsec" },
    tofu = { "tflint", "tfsec" },
    typescript = { "biomejs" },
    yaml = { "yamllint" },
  },
  debuggers = {
    "debugpy",
    "delve",
  },
}
